export const AUTH = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
};

export const BASE = {
  SET_CONFIG: 'SET_CONFIG',
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_USER_BG: 'SET_USER_BG',
  SET_USER_AVATAR: 'SET_USER_AVATAR',
  SET_BAR_HEIGHTS: 'SET_BAR_HEIGHTS',
};
