export const AUTH = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_OUT: 'SIGN_OUT',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  SET_USERS: 'SET_USERS',
};

export const BASE = {
  SET_CONFIG: 'SET_CONFIG',
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_USER_BG: 'SET_USER_BG',
  SET_USER_AVATAR: 'SET_USER_AVATAR',
  SET_BAR_HEIGHTS: 'SET_BAR_HEIGHTS',
};
